version: 2
updates:
  - package-ecosystem: 'pip'
    directory: "/"
    schedule:
      interval: 'weekly'
      time: "23:30"
    open-pull-requests-limit: 5
    commit-message:
      prefix: '[DEPENDABOT]'
    labels:
      - 'dependabot'
